# 运维模块的数据库初始化脚本

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ops_assets",
        sa.Column("uuid", sa.String(length=128), nullable=False),
        sa.Column("asset_name", sa.String(length=128), nullable=True),
        sa.Column("asset_description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_uuid"), "ops_assets", ["uuid"], unique=False)
    # ### end Alembic commands ###

    # ### 资产类型信息 ###
    assets_types_table = op.create_table(
        "ops_assets_types",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.String(length=128), nullable=True),
        sa.Column("asset_type_name", sa.String(length=128), nullable=True),
        sa.Column("asset_type_name_zh", sa.String(length=128), nullable=True),
        sa.Column("queue", sa.Integer(), nullable=False, default=0),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_types_id"), "ops_assets_types", ["id"], unique=False)
    # ### 资产类型初始化信息 ###
    op.bulk_insert(assets_types_table,
                   [
                       {'id':'603d61bb-be7b-11ef-90c8-44a842237864', 'parent_id': None, 'asset_type_name':'PART', 'asset_type_name_zh':'配件', 'queue':3, 'description':None},
                       {'id':'8fb707d8-b07e-11ef-90c8-44a842237864', 'parent_id': None, 'asset_type_name':'SERVER', 'asset_type_name_zh':'服务器', 'queue':1, 'description':None},
                       {'id':'8fbc77f1-b07e-11ef-90c8-44a842237864', 'parent_id': None, 'asset_type_name':'NETWORK', 'asset_type_name_zh':'网络设备', 'queue':2, 'description':None},
                       {'id':'abc89126-d25d-11ef-90c8-44a842237864', 'parent_id': None, 'asset_type_name':'AREATYPE', 'asset_type_name_zh':'区域类型', 'queue':4, 'description':None}
                   ]
                   )

    # ### 资产基础信息 ###
    op.create_table(
        "ops_assets_basic_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_type_id", sa.String(length=128), nullable=True),
        sa.Column("asset_category", sa.String(length=128), nullable=True),
        sa.Column("asset_type", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("equipment_number", sa.String(length=128), nullable=True),
        sa.Column("sn_number", sa.String(length=128), nullable=True),
        sa.Column("asset_number", sa.String(length=128), nullable=True),
        sa.Column("asset_status", sa.String(length=40), nullable=True),
        sa.Column("asset_status_description", sa.Text(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("extend_column_extra", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_basic_info_id"), "ops_assets_basic_info", ["id"], unique=False)

    # ### 资产配件信息 ###
    op.create_table(
        "ops_assets_parts_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("manufacturer_id", sa.String(length=128), nullable=True),
        sa.Column("part_type_id", sa.String(length=128), nullable=True),
        sa.Column("part_type", sa.String(length=128), nullable=True),
        sa.Column("part_brand", sa.String(length=128), nullable=True),
        sa.Column("part_config", sa.String(length=128), nullable=True),
        sa.Column("part_number", sa.String(length=128), nullable=True),
        sa.Column("personal_used_flag", sa.Boolean(), nullable=True),
        sa.Column("surplus", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_parts_info_id"), "ops_assets_parts_info", ["id"], unique=False)

    # ### 资产厂商信息 ###
    op.create_table(
        "ops_assets_manufactures_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_manufactures_info_id"), "ops_assets_manufactures_info", ["id"], unique=False)

    # ### 资产厂商关联关系信息 ###
    op.create_table(
        "ops_assets_manufactures_relations_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("manufacture_id", sa.String(length=128), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_manufactures_relations_info_id"), "ops_assets_manufactures_relations_info", ["id"], unique=False)

    # ### 资产位置信息 ###
    op.create_table(
        "ops_assets_positions_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("frame_position", sa.String(length=128), nullable=True),
        sa.Column("cabinet_position", sa.String(length=128), nullable=True),
        sa.Column("u_position", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_positions_info_id"), "ops_assets_positions_info", ["id"], unique=False)

    # ### 资产合同信息 ###
    op.create_table(
        "ops_assets_contracts_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("contract_number", sa.String(length=128), nullable=True),
        sa.Column("purchase_date", sa.DateTime(), nullable=True),
        sa.Column("batch_number", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_contracts_info_id"), "ops_assets_contracts_info", ["id"], unique=False)

    # ### 资产归属用户信息 ###
    op.create_table(
        "ops_assets_belongs_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("department_id", sa.String(length=128), nullable=True),
        sa.Column("department_name", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_name", sa.String(length=128), nullable=True),
        sa.Column("tel_number", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_belongs_info_id"), "ops_assets_belongs_info", ["id"], unique=False)

    # ### 资产租赁客户信息 ###
    op.create_table(
        "ops_assets_customers_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("customer_id", sa.String(length=128), nullable=True),
        sa.Column("customer_name", sa.String(length=128), nullable=True),
        sa.Column("rental_duration", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("vlan_id", sa.String(length=128), nullable=True),
        sa.Column("float_ip", sa.String(length=128), nullable=True),
        sa.Column("band_width", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_customers_info_id"), "ops_assets_customers_info", ["id"], unique=False)

    # ### 资产设备的流入流出信息 ###
    op.create_table(
        "ops_assets_flows_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("port", sa.String(length=128), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("opposite_asset_id", sa.String(length=128), nullable=True),
        sa.Column("opposite_port", sa.String(length=128), nullable=True),
        sa.Column("opposite_label", sa.String(length=255), nullable=True),
        sa.Column("cable_type", sa.String(length=128), nullable=True),
        sa.Column("cable_interface_type", sa.String(length=128), nullable=True),
        sa.Column("cable_length", sa.Integer(), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_flows_info_id"), "ops_assets_flows_info", ["id"], unique=False)

    # ### 资产设备的扩展字段信息 ###
    assets_extends_columns_table = op.create_table(
        "ops_assets_extends_columns_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_type", sa.String(length=128), nullable=True),
        sa.Column("role_type", sa.String(length=128), nullable=True),
        sa.Column("column_key", sa.String(length=128), nullable=True),
        sa.Column("column_name", sa.String(length=128), nullable=True),
        sa.Column("column_type", sa.String(length=128), nullable=True),
        sa.Column("required_flag", sa.Boolean(), nullable=True),
        sa.Column("default_flag", sa.Boolean(), nullable=True),
        sa.Column("hidden_flag", sa.Boolean(), nullable=True),
        sa.Column("queue", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_extends_columns_info_id"), "ops_assets_extends_columns_info", ["id"], unique=False)
    # ### 资产类型初始化信息 ###
    op.bulk_insert(assets_extends_columns_table,
                   [
                       # 服务器默认配置
                       {'id':'b596ad7c-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_id', 'column_name':'ID', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':0, 'description':None},
                       {'id':'b5a32c2c-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_name', 'column_name':'设备名称', 'column_type':'str', 'required_flag':1, 'default_flag':1, 'hidden_flag':0, 'queue':1, 'description':None},
                       {'id':'b5a98102-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_status', 'column_name':'资产状态', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':2, 'description':None},
                       {'id':'b5af5c71-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_type', 'column_name':'类型', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':3, 'description':None},
                       {'id':'4f06f4d3-0a12-11f0-84fe-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'frame_position', 'column_name':'机房号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':4, 'description':None},
                       {'id':'b5c07800-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'cabinet_position', 'column_name':'机柜', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':5, 'description':None},
                       {'id':'b5c58057-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'u_position', 'column_name':'U位', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':6, 'description':None},
                       {'id':'b5c9edd2-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'equipment_number', 'column_name':'设备型号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':7, 'description':None},
                       {'id':'b5d36bac-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_number', 'column_name':'资产编号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':8, 'description':None},
                       {'id':'b5d9a733-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'sn_number', 'column_name':'序列号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':9, 'description':None},
                       {'id':'b5e0d00a-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'department_name', 'column_name':'部门', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':10, 'description':None},
                       {'id':'b5e84c8d-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'user_name', 'column_name':'负责人', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':11, 'description':None},
                       {'id':'b5ee533c-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'host_name', 'column_name':'主机名', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':12, 'description':None},
                       {'id':'b5f3a4d1-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'ip', 'column_name':'IP', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':13, 'description':None},
                       {'id':'b5f8c5f4-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'idrac', 'column_name':'IDRAC', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':14, 'description':None},
                       {'id':'b601c7af-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'use_to', 'column_name':'用途', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':15, 'description':None},
                       {'id':'b6129347-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'operate_system', 'column_name':'操作系统', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':16, 'description':None},
                       {'id':'b61b907e-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'manufacturer_name', 'column_name':'厂商', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':17, 'description':None},
                       {'id':'b621f7f2-c8eb-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_description', 'column_name':'备注', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':18, 'description':None},
                       # {'id':'b7688486-cd88-11ef-90c8-44a842237864', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part', 'column_name':'配件', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':19, 'description':None},
                       {'id':'60363d30-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_cpu', 'column_name':'CPU', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':21, 'description':None},
                       {'id':'657642f3-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_cpu_cores', 'column_name':'逻辑核心数', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':22, 'description':None},
                       {'id':'6cbe7742-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_memory', 'column_name':'内存', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':23, 'description':None},
                       {'id':'70e91bd4-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_disk', 'column_name':'系统盘', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':24, 'description':None},
                       {'id':'77e4b84b-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_data_disk', 'column_name':'数据盘', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':25, 'description':None},
                       {'id':'85865485-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_nic', 'column_name':'网卡', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':26, 'description':None},
                       {'id':'86aa0242-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_gpu', 'column_name':'GPU', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':27, 'description':None},
                       {'id':'88275fea-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_ib_card', 'column_name':'IB卡', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':28, 'description':None},
                       {'id':'891a7863-0a26-11f0-8eb6-b083fee16a73', 'asset_type':'SERVER', 'role_type':None, 'column_key':'asset_part_module', 'column_name':'模块', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':29, 'description':None},

                       # 网络默认配置
                       {'id':'c59bf2bb-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_id', 'column_name':'ID', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':0, 'description':None},
                       {'id':'c5a636d4-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_name', 'column_name':'名称', 'column_type':'str', 'required_flag':1, 'default_flag':1, 'hidden_flag':0, 'queue':1, 'description':None},
                       {'id':'c5b10003-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_status', 'column_name':'状态', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':2, 'description':None},
                       {'id':'c5be0288-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_type', 'column_name':'类型', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':3, 'description':None},
                       {'id':'77c60f20-0a12-11f0-84fe-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'frame_position', 'column_name':'机房号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':4, 'description':None},
                       {'id':'c5d2cc24-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'cabinet_position', 'column_name':'机柜', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':5, 'description':None},
                       {'id':'c5df1fb1-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'u_position', 'column_name':'U位', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':6, 'description':None},
                       {'id':'c5ec3535-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'equipment_number', 'column_name':'型号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':7, 'description':None},
                       {'id':'c5f78b5a-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_number', 'column_name':'编号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':8, 'description':None},
                       {'id':'c603c734-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'sn_number', 'column_name':'序列号', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':9, 'description':None},
                       {'id':'c6100795-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'extra', 'column_name':'网络配置信息', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':9, 'description':None},
                       {'id':'c61c31be-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'department_name', 'column_name':'部门', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':10, 'description':None},
                       {'id':'c6273f56-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'user_name', 'column_name':'负责人', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':11, 'description':None},
                       {'id':'c632d180-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'host_name', 'column_name':'主机名', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':12, 'description':None},
                       {'id':'c65a3393-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'use_to', 'column_name':'用途', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':15, 'description':None},
                       {'id':'c684c110-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'manufacturer_name', 'column_name':'厂商', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':17, 'description':None},
                       {'id':'c690c3aa-c8ec-11ef-90c8-44a842237864', 'asset_type':'NETWORK', 'role_type':None, 'column_key':'asset_description', 'column_name':'备注', 'column_type':'str', 'required_flag':0, 'default_flag':1, 'hidden_flag':0, 'queue':18, 'description':None},
                   ]
                   )

    # ### 操作日志信息 ###
    op.create_table(
        "ops_operate_log",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("log_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_name", sa.String(length=128), nullable=True),
        sa.Column("ip", sa.String(length=128), nullable=True),
        sa.Column("operate_type", sa.String(length=128), nullable=True),
        sa.Column("resource_type", sa.String(length=128), nullable=True),
        sa.Column("resource_type_name", sa.String(length=128), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("resource_name", sa.String(length=128), nullable=True),
        sa.Column("operate_flag", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_operate_log_id"), "ops_operate_log", ["id"], unique=False)

    # ### 资产订单信息 ###
    op.create_table(
        "ops_assets_orders_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("order_no", sa.String(length=128), nullable=False),
        sa.Column("order_status", sa.String(length=40), nullable=False),
        sa.Column("order_type", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("user_account", sa.String(length=128), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_orders_info_id"), "ops_assets_orders_info", ["id"], unique=False)

    # ### 运维监控url配置信息 ###
    op.create_table(
        "ops_monitor_url_config_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("url_catalog", sa.String(length=40), nullable=False),
        sa.Column("url_type", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("user_account", sa.String(length=128), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_monitor_url_config_info_id"), "ops_monitor_url_config_info", ["id"], unique=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ops_assets_uuid"), table_name="ops_assets")
    op.drop_table("ops_assets")
    # ### end Alembic commands ###
