# 运维模块的数据库初始化脚本

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ops_assets",
        sa.Column("uuid", sa.String(length=128), nullable=False),
        sa.Column("asset_name", sa.String(length=128), nullable=True),
        sa.Column("asset_description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_uuid"), "ops_assets", ["uuid"], unique=False)
    # ### end Alembic commands ###
    # ### 资产类型信息 ###
    op.create_table(
        "ops_assets_types",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.String(length=128), nullable=True),
        sa.Column("asset_type_name", sa.String(length=128), nullable=True),
        sa.Column("asset_type_name_zh", sa.String(length=128), nullable=True),
        sa.Column("queue", sa.Integer(), nullable=False, default=0),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_types_id"), "ops_assets_types", ["id"], unique=False)
    # ### 资产基础信息 ###
    op.create_table(
        "ops_assets_basic_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_type_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("equipment_number", sa.String(length=128), nullable=True),
        sa.Column("sn_number", sa.String(length=128), nullable=True),
        sa.Column("asset_number", sa.String(length=128), nullable=True),
        sa.Column("asset_status", sa.String(length=40), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_basic_info_id"), "ops_assets_basic_info", ["id"], unique=False)
    # ### 资产配件信息 ###
    op.create_table(
        "ops_assets_manufactures_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("extra", sa.Text(), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_manufactures_info_id"), "ops_assets_manufactures_info", ["id"], unique=False)
    # ### 资产位置信息 ###
    op.create_table(
        "ops_assets_positions_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("frame_position", sa.String(length=128), nullable=True),
        sa.Column("cabinet_position", sa.String(length=128), nullable=True),
        sa.Column("u_position", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_positions_info_id"), "ops_assets_positions_info", ["id"], unique=False)
    # ### 资产合同信息 ###
    op.create_table(
        "ops_assets_contracts_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("contract_number", sa.String(length=128), nullable=True),
        sa.Column("purchase_date", sa.DateTime, nullable=True),
        sa.Column("batch_number", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_contracts_info_id"), "ops_assets_contracts_info", ["id"], unique=False)
    # ### 资产归属用户信息 ###
    op.create_table(
        "ops_assets_belongs_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("department_id", sa.String(length=128), nullable=True),
        sa.Column("department_name", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("user_name", sa.String(length=128), nullable=True),
        sa.Column("tel_number", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_belongs_info_id"), "ops_assets_belongs_info", ["id"], unique=False)
    # ### 资产租赁客户信息 ###
    op.create_table(
        "ops_assets_customers_info",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=True),
        sa.Column("customer_id", sa.String(length=128), nullable=True),
        sa.Column("customer_name", sa.String(length=128), nullable=True),
        sa.Column("rental_duration", sa.Integer, nullable=True),
        sa.Column("start_date", sa.DateTime, nullable=True),
        sa.Column("end_date", sa.DateTime, nullable=True),
        sa.Column("vlan_id", sa.String(length=128), nullable=True),
        sa.Column("float_ip", sa.String(length=128), nullable=True),
        sa.Column("band_width", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_ops_assets_customers_info_id"), "ops_assets_customers_info", ["id"], unique=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ops_assets_uuid"), table_name="ops_assets")
    op.drop_table("ops_assets")
    # ### end Alembic commands ###
